services:
  server:
    container_name: library    
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - 8080:8080
    depends_on:
      - sqlserver
    develop:
      watch:
        - action: rebuild
          path: .
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "An@5ophia"
    ports:
      - "1433:1433"
    volumes:
      - C:/Users/georg/OneDrive/Area de Trabalho/LivrariaWaldemar/LibraryApp/mssql/:/var/opt/mssql/data/
    networks:
      - mynetwork

networks:
  mynetwork:  
    driver: bridge