services:
  server:
    image: geeuzebio/wflibrary:newest
    container_name: library
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      db:
        condition: service_healthy
    networks:
     - mynetwork
  
  db:
    image: postgres
    container_name: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=wflibrary
      - POSTGRES_PASSWORD=An@5ophia
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "wflibrary" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
     - mynetwork

volumes:
  db-data:

networks:
  mynetwork:  
    driver: bridge