services:
  server:
    container_name: library    
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - 8080:8080
    depends_on:
      sqlserver:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "An@5ophia"
    ports:
      - "1433:1433"
    volumes:
      - C:/Users/georg/OneDrive/Area de Trabalho/LivrariaWaldemar/LibraryApp/mssql/:/var/opt/mssql/data/
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-Slocalhost", "-Usa", "-PAn@5ophia","-Q","SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mynetwork:  
    driver: bridge